

all: memwrite memread memdump

memwrite: memwrite.cpp
	g++ -O2 memwrite.cpp -o memwrite

memread: memread.cpp
	g++ -O2 memread.cpp  -o memread

memdump: memdump.cpp
	g++ -O2 memdump.cpp  -o memdump
