
# in_clk125
create_clock -period 8.000 -name in_clk125 -waveform {0.000 4.000} [get_ports in_clk125]

set_property PACKAGE_PIN K17 [get_ports in_clk125]
set_property IOSTANDARD LVCMOS33 [get_ports in_clk125]

set_property PACKAGE_PIN K18 [get_ports in_reset]
set_property PACKAGE_PIN P16 [get_ports {push_sw[1]}]
set_property PACKAGE_PIN K19 [get_ports {push_sw[2]}]
set_property PACKAGE_PIN Y16 [get_ports {push_sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports in_reset]
set_property IOSTANDARD LVCMOS33 [get_ports {push_sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {push_sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {push_sw[3]}]

set_property PACKAGE_PIN V12 [get_ports bldc_ap_en]
set_property PACKAGE_PIN W16 [get_ports bldc_an_en]
set_property PACKAGE_PIN J15 [get_ports bldc_bp_en]
set_property PACKAGE_PIN H15 [get_ports bldc_bn_en]
set_property PACKAGE_PIN V13 [get_ports bldc_ap_hl]
set_property PACKAGE_PIN U17 [get_ports bldc_an_hl]
set_property PACKAGE_PIN T17 [get_ports bldc_bp_hl]
set_property PACKAGE_PIN Y17 [get_ports bldc_bn_hl]
set_property IOSTANDARD LVCMOS33 [get_ports bldc_ap_en]
set_property IOSTANDARD LVCMOS33 [get_ports bldc_an_en]
set_property IOSTANDARD LVCMOS33 [get_ports bldc_bp_en]
set_property IOSTANDARD LVCMOS33 [get_ports bldc_bn_en]
set_property IOSTANDARD LVCMOS33 [get_ports bldc_ap_hl]
set_property IOSTANDARD LVCMOS33 [get_ports bldc_an_hl]
set_property IOSTANDARD LVCMOS33 [get_ports bldc_bp_hl]
set_property IOSTANDARD LVCMOS33 [get_ports bldc_bn_hl]

set_property PACKAGE_PIN G15 [get_ports {dip_sw[0]}]
set_property PACKAGE_PIN P15 [get_ports {dip_sw[1]}]
set_property PACKAGE_PIN W13 [get_ports {dip_sw[2]}]
set_property PACKAGE_PIN T16 [get_ports {dip_sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dip_sw[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dip_sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dip_sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dip_sw[3]}]

set_property PACKAGE_PIN M14 [get_ports {led[0]}]
set_property PACKAGE_PIN M15 [get_ports {led[1]}]
set_property PACKAGE_PIN G14 [get_ports {led[2]}]
set_property PACKAGE_PIN D18 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
