create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 1 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list mii_refclk_0_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {axi4s_eth_tx_tvalid[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {axi4s_eth_tx_tready[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {axi4s_eth_tx_tlast[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {axi4s_eth_tx_tdata[0][0]} {axi4s_eth_tx_tdata[0][1]} {axi4s_eth_tx_tdata[0][2]} {axi4s_eth_tx_tdata[0][3]} {axi4s_eth_tx_tdata[0][4]} {axi4s_eth_tx_tdata[0][5]} {axi4s_eth_tx_tdata[0][6]} {axi4s_eth_tx_tdata[0][7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {axi4s_eth_rx_tdata[0][0]} {axi4s_eth_rx_tdata[0][1]} {axi4s_eth_rx_tdata[0][2]} {axi4s_eth_rx_tdata[0][3]} {axi4s_eth_rx_tdata[0][4]} {axi4s_eth_rx_tdata[0][5]} {axi4s_eth_rx_tdata[0][6]} {axi4s_eth_rx_tdata[0][7]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 1 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list mii_refclk_1_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {axi4s_eth_tx_tvalid[1]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {axi4s_eth_tx_tready[1]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list {axi4s_eth_tx_tlast[1]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 8 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list {axi4s_eth_tx_tdata[1][0]} {axi4s_eth_tx_tdata[1][1]} {axi4s_eth_tx_tdata[1][2]} {axi4s_eth_tx_tdata[1][3]} {axi4s_eth_tx_tdata[1][4]} {axi4s_eth_tx_tdata[1][5]} {axi4s_eth_tx_tdata[1][6]} {axi4s_eth_tx_tdata[1][7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 8 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list {axi4s_eth_rx_tdata[1][0]} {axi4s_eth_rx_tdata[1][1]} {axi4s_eth_rx_tdata[1][2]} {axi4s_eth_rx_tdata[1][3]} {axi4s_eth_rx_tdata[1][4]} {axi4s_eth_rx_tdata[1][5]} {axi4s_eth_rx_tdata[1][6]} {axi4s_eth_rx_tdata[1][7]}]]
create_debug_core u_ila_2 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_2]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_2]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_2]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_2]
set_property C_INPUT_PIPE_STAGES 1 [get_debug_cores u_ila_2]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
connect_debug_port u_ila_2/clk [get_nets [list i_design_1/clk_wiz_0/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property port_width 2 [get_debug_ports u_ila_2/probe0]
connect_debug_port u_ila_2/probe0 [get_nets [list {axi4s_eth_tx_tvalid[2]} {axi4s_eth_tx_tvalid[3]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe1]
set_property port_width 2 [get_debug_ports u_ila_2/probe1]
connect_debug_port u_ila_2/probe1 [get_nets [list {axi4s_eth_tx_tready[2]} {axi4s_eth_tx_tready[3]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe2]
set_property port_width 2 [get_debug_ports u_ila_2/probe2]
connect_debug_port u_ila_2/probe2 [get_nets [list {axi4s_eth_tx_tlast[2]} {axi4s_eth_tx_tlast[3]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe3]
set_property port_width 8 [get_debug_ports u_ila_2/probe3]
connect_debug_port u_ila_2/probe3 [get_nets [list {axi4s_eth_tx_tdata[3][0]} {axi4s_eth_tx_tdata[3][1]} {axi4s_eth_tx_tdata[3][2]} {axi4s_eth_tx_tdata[3][3]} {axi4s_eth_tx_tdata[3][4]} {axi4s_eth_tx_tdata[3][5]} {axi4s_eth_tx_tdata[3][6]} {axi4s_eth_tx_tdata[3][7]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe4]
set_property port_width 8 [get_debug_ports u_ila_2/probe4]
connect_debug_port u_ila_2/probe4 [get_nets [list {axi4s_eth_tx_tdata[2][0]} {axi4s_eth_tx_tdata[2][1]} {axi4s_eth_tx_tdata[2][2]} {axi4s_eth_tx_tdata[2][3]} {axi4s_eth_tx_tdata[2][4]} {axi4s_eth_tx_tdata[2][5]} {axi4s_eth_tx_tdata[2][6]} {axi4s_eth_tx_tdata[2][7]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe5]
set_property port_width 8 [get_debug_ports u_ila_2/probe5]
connect_debug_port u_ila_2/probe5 [get_nets [list {axi4s_eth_rx_tdata[3][0]} {axi4s_eth_rx_tdata[3][1]} {axi4s_eth_rx_tdata[3][2]} {axi4s_eth_rx_tdata[3][3]} {axi4s_eth_rx_tdata[3][4]} {axi4s_eth_rx_tdata[3][5]} {axi4s_eth_rx_tdata[3][6]} {axi4s_eth_rx_tdata[3][7]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe6]
set_property port_width 8 [get_debug_ports u_ila_2/probe6]
connect_debug_port u_ila_2/probe6 [get_nets [list {axi4s_eth_rx_tdata[2][0]} {axi4s_eth_rx_tdata[2][1]} {axi4s_eth_rx_tdata[2][2]} {axi4s_eth_rx_tdata[2][3]} {axi4s_eth_rx_tdata[2][4]} {axi4s_eth_rx_tdata[2][5]} {axi4s_eth_rx_tdata[2][6]} {axi4s_eth_rx_tdata[2][7]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets sys_clk100]
