

SIM_LIB_DIRS ?=

SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v1/bus
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v1/cache
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v1/dma
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v1/gpu
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v1/image
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v1/legacy
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v1/library
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v1/math
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v1/mipsi
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v1/misc
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v1/model
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v1/peripheral
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v1/primitive
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v1/video

SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v2/bus
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v2/dma
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v2/gpu
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v2/image
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v2/jfive
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v2/library
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v2/math
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v2/misc
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v2/model
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v2/network
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v2/primitive
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v2/peripheral
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v2/rtos
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v2/video

SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v3/package
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v3/interface
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v3/bus
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v3/dma
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v3/gpu
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v3/image
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v3/jfive
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v3/library
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v3/math
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v3/misc
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v3/model
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v3/network
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v3/primitive
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v3/peripheral
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v3/rtos
SIM_LIB_DIRS += $(JELLY_TOP_DIR)/rtl/v3/video
