


.PHONY: all
all: build

.PHONY: build
build:
	cargo build

.PHONY: clean
clean:
	cargo clean

.PHONY: run
run:
#	cargo run
	-xterm -e "cargo run --release"

.PHONY: stop
stop:
